valuesFilePath: ./values.yml
pipelines:
- name: test_pipeline
  configuration:
    jfrogCliVersion: 2
  steps:
    - name: test_step
      type: powershell
      execution:
        onStart:
          - echo {{ .Values.isTestPipeline }}
        