pipelines:
  - name: HelloWorldPipeline
    steps:
      - name: HelloWorldStep
        type: powershell
        configuration:
          platform:
            os: windows
        execution:
          onExecute:
            - script: |
                Write-Host "Hello, World!"
